
export default {
    html: `<h1>
    PART V - FINAL CONSIDERATIONS FOR ABBREVIATED GENEALOGIES
</h1>
<h1>
    Chapter Twelve
</h1>
<p align="center">
    <strong>Biblical Earth Movements After the Flood</strong>
</p>
<h1 align="left">
    The Bible commends faith. But Scripture also requires a correct object for
    faith. Christians are well aware of the disasters resulting from faith in
    Jim Jones and Joseph Smith. Faith in Jones took the lives of 900
    individuals while faith in Smith perpetuates a false gospel. This book
    seeks to show that a complete faith that accepts the global Flood of Noah's
    day must include the way Scripture used Hebrew genealogies. This chapter
    addresses the over simplified belief the that major earth movements were
    complete by the Flood's end. The most graphic representation of such
    over-literal faith has the ark passengers descending from the top of Great
    Ararat which is 16,900 feet above sea level. Meanwhile it overlooks such
    events as the fire of God which took Job's 7000 sheep over a thousand years
    after the Flood, the deepening of the Syro-African Rift in the Jordan
    Valley 2000 years after the Flood and even such secular memories as the
    lost city of Atlantis.
</h1>
<h1 align="left">
    Scripture identifies two events that brought on the Flood: "all the
    fountains of the great deep burst forth" and "the windows of the heavens
    were opened" (Genesis 7:11). As a result, rain fell on the earth, ocean
    floors rose and continents sank until the ark floated (7:18). Through these
    processes the water continued to rise until "all the high mountains under
    the whole heaven were covered" (7:19). After 150 days of rising flood
    waters, God took actions which stopped the Flood and removed the water.
    Scripture summarizes with "The fountains of the deep and the windows of
    heaven were closed, the rain from heaven was restrained, and the waters
    receded from the earth continually" (8:2-3). This, too, was not immediate
    but was a process.
</h1>
<p>
    Scripture gives the following detail of timing: The rain began "In the six
    hundredth year of Noah's life, in the second month, on the seventeenth day
    of the month" (Genesis 7:11). At day 150 God closed the fountains of the
    deep and the windows of heaven (Genesis 8:1-2). At day 314 the waters were
    dried from off the earth (Genesis 8:13). But the ground was dangerously
    wet. At day 370, the earth had dried out (Genesis 8:14). "Then God said to
    Noah, 'Go out from the Ark&#8230;.' So Noah went out, and his
    sons&#8230;everything that moves on the earth went out" (Genesis 8:15, 18).
    The Flood itself was a process that involved time, over one year.
</p>
<p>
    The above verses assure us that four families and all air-breathing land
    creatures had been preserved in the Ark. They also record the timing and
    receding of the Flood. The Flood was the most earth-changing event in all
    history. But to take from these verses that all earth movements ended on
    day 370 of the Flood is an overreach of faith. The following pages will
    cite numerous instances of continuing earth movements.
</p>
<p>
    <a name="_Hlk69827299"><strong>Location of the Ark </strong></a>
</p>
<p>
    "The ark came to rest on the mountains of Ararat" (Genesis 8:4). Since the
    highest peak in the Ararat range is Great Ararat at 16,945', tradition and
    many Christians declare Great Ararat as the landing place of Noah's ark
    since the Ark came to rest several months before any other mountains were
    visible. But further information gives a very different picture. First,
    Great Ararat and Little Ararat (12,782') which is eleven miles distant are
    volcanoes. In fact, the entire region is volcanic. The plain to the
    southwest of Great Ararat rises to 5000 feet above sea level while the
    broad alluvial plain north and east of Great Ararat rises to 3300 feet
    above sea level. Most importantly, the editor Moses wrote about 1400 BC, so
    the Ararat Range had two and a half millennia after the Flood to rise to
    the height of a mountain range.
</p>
<p>
    For the entire ark contingent of thousands of creatures plus the eight
    adults to climb down from the mountain and settle in some valley is an idea
    generated by over-literalism. Noah and his family would have used supplies
    on the Ark to reestablish life. Making hundreds of trips back up the
    mountain for all those supplies and materials would have been impossible.
    What actually happened? God provided a hill higher than the other hills for
    the Ark's landing. Noah's family established a community on or near that
    hill and began farming. As time passed volcanic eruptions in the area
    persuaded the family to seek a safer habitat. As they safely exited the
    area volcanic activity began forming mountains. As recently as 1840 AD
    Great Ararat erupted and lava flowed to increase its size. Today the Ararat
    range with its high plateaus is the result of 6000 years of volcanic
    activity.
</p>
<p>
    <strong>Collapse of the Jordan Valley </strong>
</p>
<p>
    Two thousand years after the Flood, the Jordan Valley still resembled the
    fertile Nile River Valley. Scripture even likens the Jordan Valley to the
    Garden of Eden. This disclosure comes at the time Abraham and Lot parted
    company because their herdsmen were fighting over the available land. Then
    a violent act of nature left the valley desolate. Here is how the area
    looked before this happened:
</p>
<p>
    <strong>
        <sup>8</sup>
        Then Abram said to Lot, "Let there be no strife between you and me, and
        between your herdsmen and my herdsmen, for we are kinsmen. <sup>9</sup>
        Is not the whole land before you? Separate yourself from me. If you
        take the left hand, then I will go to the right, or if you take the
        right hand, then I will go to the left." <sup>10</sup>And Lot lifted up
        his eyes and saw that the Jordan Valley was well watered everywhere
        like the garden of the LORD, like the land of Egypt, in the direction
        of Zoar. Genesis 13:8-10.
    </strong>
</p>
<p>
    In Egypt the Nile overflowed its banks each summer as it carried water to
    the sea from the winter rains to the south. In doing so it fertilized the
    soil with a layer of thick, rich silt and replenished ground moisture,
    providing life-giving moisture to crops to be planted and causing life to
    flourish in this dry area. Without life-giving water ancient Egypt with its
    pyramids, temples and tombs would not have existed. The same was true with
    that first garden God planted for Adam. A river flowed through the garden
    and divided into four rivers, so great was the quantity of water God
    supplied.
</p>
<p>
    In the same way the land Lot chose thrived because it had an abundance of
    water. Scripture uses two words to describe the unusual quantity of water.
    When it says the land was watered, it adds the adverb "well." The land was
    well watered. But that still was inadequate so the word "everywhere" was
    added. Lot saw the Jordan Valley to be "well-watered everywhere." It wasn't
    just the river that watered the valley because the valley was broad, a
    plain. In addition to the generous amount of water supplied by the river,
    it received an abundance of rain. Consequently, this valley was green,
    lush, ideal for Lot's herds. Then Scripture adds those two other lands
    known for their abundant watering. The Jordan Valley was watered like that
    original garden God planted for man and like the well-watered land of Egypt
    in that day.
</p>
<p>
    Following this highly favorable description of the Jordan Valley, Scripture
    adds an onerous parenthesis: "This was before the LORD destroyed Sodom and
    Gomorrah." Just 20 or so years after Lot chose the lush Jordan Valley, God
    told him to leave it immediately and flee to the eastern hills. The next
    morning the destruction began. It was an awesome earth movement. The two
    sides to the valley moved in such a way that the valley dropped enough to
    become the lowest place on earth. The event was accompanied by, an
    unleashing of molten lava called "fire and brimstone."
</p>
<p>
    Lot first took refuge in a town on the edge of the pentapolis. But then he
    moved to the hills God originally told him to flee to. While his time in
    that small town may have been short, maybe just long enough to get some
    rest, it shows that this earth movement was a process. It progressed over
    time. In the morning it took Sodom and Gomorrah. As it crept closer to the
    nearby town Lot had begged to stay in, Lot changed his mind and journeyed
    into the hills, out of the valley. Whether this was a day or a week, it
    indicates that a process was going on. In the end Lot became a cave man and
    his two daughters spoke of a scarcity of men. This speaks of the desolation
    of the area.
</p>
<p>
    The event took most life in the area, caused the floor of the plain to drop
    into the earth and left the area a permanent blight on the face of the
    earth. Abraham lived on a 2600' high plateau above this area. Even though
    he had lived there for 15 or so years and had good relations with the
    resident Amorites, he moved away. Why? Scripture doesn't say but most
    likely the continuing smoke, fire and brimstone, earthquakes, etc.,
    compelled him to find a quieter area for his people and vast herds and
    flocks.
</p>
<p>
    The formation that this event produced or enlarged is called the
    Syro-African Rift. While the tearing away of these two enormous chunks of
    earth on either side of the broad plain may have started at the time of the
    Flood, the work was not completed until 2000 years later. Because Scripture
    documents so completely the before and after, this represents an undeniable
    earth movement long after the Flood. Historically, few have really taken
    Scripture's "before" description seriously. These 500 or so words are given
    to help believers to grasp the gravity of this event. It was not just a
    volcanic eruption. It was the movement of two enormous blocks of the
    surface of the earth and it mostly happened over a period of years in as
    much as Lot is left living in a cave and his two sons remain in those hills
    rather than moving to that formerly fertile valley. Today, apart from
    irrigation, that area is barren and even features a sea of salt. While
    there had been eruptions before and an area of tar pits was not hospitable
    to man, it only became desolate with this event.
</p>
<p>
    <strong>Major Earth Movements Cited in Job </strong>
</p>
<p>
    Entirely overlooked and explained as poetic license are the eye-popping
    earth movements found in the Book of Job. The best known is the volcanic
    eruption that took away his sheep. Job 1:16 relates the event:
    "&#8230;There came another (messenger) and said, 'The fire of God fell from
    heaven and burned up the sheep and the servants and consumed them and I
    alone have escaped to tell you.'" The messenger had a term for the event.
    It was a part of his vocabulary which indicates that it happened frequently
    enough that it was a part of that area's vocabulary. He called it "the fire
    of God." This was 1500 years after the Flood. While this is not an earth
    movement as such, it is commonly accompanied by earth movements.
</p>
<p>
    Job had 7000 sheep. A rule of thumb was one shepherd for each 100 sheep
    which were kept in separate flocks and scattered widely so as not to
    overgraze. With the keepers would have been supervisors and support and
    possibly even older sons maybe several hundred servants in all. Job's ranch
    is described in chapter nine. It was mostly desolate and rocky, covering
    possibly 1000 square miles. We estimate that his sheep required about 15
    square miles of grassland. The grassland would be scattered over the ranch,
    so for this volcanic eruption to be 100% lethal over such a vast area would
    require a significant event.
</p>
<p>
    Another messenger arrived to report "'Your sons and daughters were eating
    and drinking wine in their oldest brother's house. And behold a great wind
    came across the wilderness and struck the four corners of the house, and it
    fell upon the young people, and they are dead, and I alone have escaped to
    tell you'" (1:18-19). These ten children of Job are called "young people."
    That is a relative term. They are young in comparison to Job who was a
    generation older. They were his young people. Actually, they were
    semi-retired and spent much of their time enjoying each other's company.
</p>
<p>
    Further they were not in a tent but in a house. His children would have
    imitated Job's care in what he did, so this house would have been
    well-built. It would have been made of stone so it would be cool during the
    hot weather. It would also be strong because strong winds characterized the
    storms of the time. Today the force of winds is rated according to wind
    speed and atmospheric pressure with a category five condition being the
    strongest. Satan managed to produce a wind speed and atmospheric pressure
    that collapsed the entire stone house. At the party were all ten of Job's
    children, so it is likely that other family members were present as well as
    a host of servants. The collapsing house killed every last person in it
    except for a single servant.
</p>
<p>
    The event could have been accompanied by an unmentioned earthquake. The
    fire of God and a wind greater than those of today indicate a time of
    heightened natural conditions and is consistent with greater earth
    movements than today. By our estimates Job was born about 1400 years after
    the Flood, in the final days of the Ice Age. Since these two unique events
    don't happen in today's world, we can more readily accept other statements
    in the book of Job that are dismissed as exaggerations or figures of
    speech.
</p>
<p>
    Repeated references are made to lightning and thunder. Job, Elihu and God
    Himself all mention lightning and thunder and the thunder is said to be the
    voice of God. Elihu said the most about them:
</p>
<p>
    <strong>
        <sup>1</sup>
        At this my heart trembles and leaps out of its place. <sup>2</sup>Keep
        listening to the thunder of his voice and the rumbling that comes from
        his mouth. <sup>3</sup>Under the whole heaven he lets it go, and his
        lightning to the corners of the earth. <sup>4</sup>After it his voice
        roars; he thunders with his majestic voice, and does not restrain the
        lightnings when his voice is heard. <sup>5</sup>God thunders wondrously
        with his voice&#8230; Job 37:1-5.
    </strong>
</p>
<p>
    Job asked, "The thunder of his power, who can understand?" (26:14). Later,
    God asked Job, "Can you thunder with a voice like his (God's)? (40:9).
    Indeed, God is the creator of all so He is the creator of the sound caused
    by His creation. In this way the idea of thunder being the voice of God is
    acceptable. No one would question that Elihu, Job and God are pointing to
    literal lightning and thunder. Thus, it is reasonable to conclude that when
    a speaker in Job refers to an act of nature, the speaker is referring to a
    literal event.
</p>
<p>
    Now, let us apply that idea to the following verse: "How can a man be right
    before God? &#8230;He who removes mountains, and they know it not, when he
    overturns them in his anger&#8230;" (Job 9:2, 5). God moved mountains in
    Job's day? Yes. Further, Job says they are turned upside down. It was not
    difficult to accept that the speakers above were pointing to literal
    lightning and thundering. But to accept that Job was speaking of literal
    mountains being removed and even overturned pictures a world far different
    from today. Today that rarely happens. But in Job's day it was a part of
    life. Over a thousand years after the Flood, mountains were commonly
    overturned. Here was evidence beyond dispute that God was powerful and no
    man could oppose his power.
</p>
<p>
    But maybe this is overreach. Maybe some mountains appeared upside down, so
    the idea was spread that God had overturned them. Possibly, except Job is
    not done speaking. He began this response by agreeing with Bildad on God's
    power. His next statement seems to confirm that in his day mountains were
    overturned. He says in verse 6 "Who shakes the earth out of its place, and
    its pillars tremble." Here is the cause of overturned
    mountains-earthquakes. But who hears of an earthquake that shakes the earth
    out of its place, that causes the entire planet to shake today? When these
    earthquakes occurred in Job's day, the people in his part of the world
    attributed them to God and they showed God was so powerful that it was
    hopeless to think of opposing him. Without question there was much earth
    movement during the Flood, but it obviously did not end with the Flood.
</p>
<p>
    In the discourse of Job chapter 14, erosion is used to illustrate how Job's
    hope is being worn away. But the erosion Job speaks of is far greater than
    current erosion rates. Job says, "But the mountain falls and crumbles away,
    and the rock is removed from its place; the waters wear away the stones;
    the torrents wash away the soil of the earth; so you destroy the hope of
    man" (14:18-19). In Job's day erosion caused entire mountains to crumble.
    This is super erosion. It was not confined to the waters of the Flood. Such
    erosion was still happening in Job's day, possibly 1500 years after the
    Flood. The Ice Age generated such rain storms. They were so powerful they
    are called hypercanes, a super hurricane. One was modeled. It showed up to
    300 inches of rain would fall in 18 days.
</p>
<p>
    These places and acts of nature in Job must be genuine since no one
    questions the following natural elements found in Job: land of Uz (1:1),
    the earth (1:7), deep darkness/thick clouds (22:13-14), cold (24:7),
    drought/heat (24:19), full moon (26:9), snow (37:6), ice (37:9), hail
    (38:22), dew (38:28), frost (38:29), ocean surface frozen (38:30).
</p>
<p>
    In conclusion the Flood did not complete the reshaping of the world. This
    process continued for centuries and even millennia after the Flood. Any
    other take on the statements above is a rejection of those portions of
    Scripture and a denial of inerrancy. Scripture urges sound faith. Sound
    faith recognizes earth movements after the Flood that continued for a
    considerable time but slowly diminished to the frequency of modern times.
</p>
<p>
    <strong>Processes During the Flood </strong>
</p>
<p>
    The following section is provided as a reminder that even during the Flood,
    God used processes. For starters, the Flood took months to cover the
    highest mountains/hills, not an instant. No known commentary discusses how
    fast the water would have to rise and for good reason. To do so one would
    first have to know the elevation of the highest mountain before the Flood
    as well as how much of the rising water was due to the lifting of ocean
    floors and/or sinking continents. None of these facts is available. But it
    is sobering to realize that rainfall as fast as one inch an hour would only
    produce a rise of two feet a day.
</p>
<p>
    According to the Guinness Book of Records, the most rain in 24 hours ever
    recorded was 71.8" (i.e., six feet). It fell on January 7-8, 1966 during a
    tropical cyclone at the 9600' level of a French territory Island in the
    Indian Ocean. That is approximately three inches an hour. If that record
    rate continued for the entire first forty days of the Flood, it would only
    raise sea level by 240 feet, hardly enough to cover mile-high mountains.
    More likely the amount of rain that fell per hour was many times the modern
    record. If 12 inches fell per hour, sea level would rise 960' in 40 days.
    But imagine what that would do to the roof of the Ark.
</p>
<p>
    Sinking land masses and rising ocean floors is another possible way to
    raise sea level. The opening of the fountains of the great deep is listed
    first in the biblical text while the opening of the windows of heaven is
    mentioned second. The windows of heaven gave rain but Scripture does not
    tell what the fountains of the deep gave. Possibly they involved massive
    molten rock pouring up from the mantle into ocean floors, thereby raising
    sea level in a second way. This would explain why ocean floor crust is
    generally younger than land crust. Secular geologists find former mantle
    rock in many places on the surface of the earth, so in the past, magma did
    rise to the surface of the earth's crust. The ocean floor is only a dozen
    or so miles above the mantle whereas the surface of land generally is about
    five times as much. This would be another reason for much of the magma
    rising into the ocean rather than on land. Maybe those fountains raised sea
    level considerably more than the rain from the windows of heaven.
</p>
<p>
    Without question unimaginable earth movements occurred during the Flood.
    But accounts in Scripture indicate earth movements continued after the
    Flood. While their frequency and intensity decreased with time, the record
    of Scripture leaves little doubt but that they did continue. Their activity
    is clearly seen in the physical appearance of today's earth surface.
</p>
<br clear="all"/>
<p>
    <strong> </strong>
</p>`}